server:
  port : 8083

parcom:
  services:
    classroom:
      host: pc-classroom
      port: 8080
  notifier:
    agents:
      -
        name: email
        host: pc-notifier-agent-email
        port: 8084
      -
        name: push
        host: pc-notifier-agent-push
        port: 8085

spring:
  application.name: pc-notifier
  hateoas:
    use-hal-as-default-json-media-type: false
  data:
    rest:
      detection-strategy: annotated
