server:
  port : 8083
  servlet:
    context-path: /api/${parcom.api.version}

parcom:
  kafka:
    bootstrap-address: pc-kafka:9092
    topic:
      notification: notification
      notificationAgent: notificationAgent
    group:
      notifier: notifier


  api:
    version: v1
  services:
    -
      name: classroom
      host: pc-classroom
      port: 8080
      version: v1

spring:
  application:
     name: pc-notifier
  hateoas:
    use-hal-as-default-json-media-type: false

management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: "health,prometheus"
