server:
  port : 8083
  servlet:
    context-path: /api/${parcom.api.version}

parcom:
  api:
    version: v1
  services:
    -
      name: classroom
      host: pc-classroom
      port: 8080
      version: v1
    -
      name: notifier-agent-email
      host: pc-notifier-agent-email
      port: 8084
      version: v1
    -
      name: notifier-agent-push
      host: pc-notifier-agent-push
      port: 8085
      version: v1
  notifier:
    agents:
      -
        name: notifier-agent-email
      -
        name: notifier-agent-push

spring:
  application.name: pc-notifier
  hateoas:
    use-hal-as-default-json-media-type: false
  data:
    rest:
      detection-strategy: annotated
